
trigger:
- main

jobs:
- job: Job_1
  displayName: Publish
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: False
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: drop'
    inputs:
      PathtoPublish: 'datalake'
      ArtifactName: 'drop'
      publishLocation: 'Container'